name: frenchiegames_website
description: Frenchie Games Website

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sprintf: ^7.0.0
  url_launcher: ^6.1.6
  rich_clipboard: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/strings/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: dosis
      fonts:
        - asset: assets/fonts/Dosis_Light.ttf
          weight: 300
        - asset: assets/fonts/Dosis_Regular.ttf
          weight: 400
        - asset: assets/fonts/Dosis_ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Dosis_Medium.ttf
          weight: 500
        - asset: assets/fonts/Dosis_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Dosis_Bold.ttf
          weight: 700